app:
  env: "development"
  port: 8080
  debug: true

mongodb:
  connection: "mongodb://r1.example.net:27017,r2.example.net:27017/"

mysqldb:
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  database: "service"

log:
  level: "debug"
  format: "json"